### ISSUE TITLE
Webhook Returns 500 internal Error

### ISSUE THREAD

**Issue by Crashdummyy** [tfsaggregator/tfsaggregator-webhooks#10]
Hey there,

i followed the install Instructions and installed the Aggregator.
But whenever I try to send Testdata I always get an 500 Internal Error.

When I install it without SSL-Cartificate I always get the "Basic authentication requires secure Connection" error. I did bind the Website to https://<address>:9999 and set SSL to "not required" inside iis-manager.
I got it to work a few operations, yet without touching any Settings it eventually stopped working.

I Want to install it on a local TFS without internet Connection

**Comment by giuliov** [comment]
The _Test_ button cannot work: it sends bogus data (esp. URLs) that Aggregator tries to use.

I tested your scenario (TFS on-prem with Aggregator on another machine on-prem) and it should work after you properly setup SSL.

**Comment by Crashdummyy** [comment]
Well I can't seem to get it to work.
What do I need to write into the Policy file ?
`<authentication autoImpersonate="false" />` 
won't work.
Testing with the Console App appears to work

EDIT: I know the Button won't work, the Problem is I always get this error while trying to use a policy

**Comment by giuliov** [comment]
The Console app is not meaningful: the rules run in the Console process and the TFS event is mocked.

I agree that it is not easy to setup this scenario, you must follow carefully the steps (and maybe I missed something)
I think it will be easier to discuss on the slack channels.
