### ISSUE TITLE
Setup failed

### ISSUE THREAD

**Issue by tonymk** [tfsaggregator/tfsaggregator-webhooks#14]
Pushed deploy to azure => seems to hang on this picture. With an angular error.

![image](https://user-images.githubusercontent.com/8872778/34605338-8000566a-f20b-11e7-8a9e-0289c51536c0.png)

**Comment by B3nCr** [comment]
I get slightly further than that, the deployment created the resource group but failed when modifying the web config by the looks of things. I'll redeploy again and post more info but there's very little I can post because the error message is "An error occurred"

**Comment by giuliov** [comment]
I am sorry, but we cannot do much about it.
The "Deploy to Azure" button is outside our control: the deploy technology is Slingshot (https://github.com/projectkudu/slingshot) and suggest to open an Issue there. In the Azure deployment logs there should be some indication of the error.
In my experience it may fails, often temporarily, on some Azure Regions; in fact I run it multiple times and it works fine for me (I usually point the Location to West Europe).
If you go to our doc site (https://tfsaggregator.github.io) you can find some instructions for manual deploy.
