### ISSUE TITLE
Failed to communicate with TFS

### ISSUE THREAD

**Issue by mbendtsen** [tfsaggregator/tfsaggregator-webhooks#15]
I am trying to install TFS aggregator as a Web Service version 2.3.

I have setup the WebApplication on IIS. First I did it using HTTP. Then when trying to configure the service hook it told me to use HTTPS if using Basic Authentication. Then I set up SSL for TFS Aggregator., but using a self-made certificate. 
Get the following error message: `The remote certificate is invalid according to the validation procedure.`
Is there any solution where I do not use Basic Authentication? Or do I have to use a trusted certificate?

**Comment by jessehouwing** [comment]
You can install the self made cert in the trusted certs store of the user
or machine.

**Comment by mbendtsen** [comment]
Okay, finally got this to work.
Now I am back to the `Basic authentication requires a secure connection to the server` error. 

These are my steps:

1. Created self-signed certificate and added to trusted cert
2.  Assigned certificate to the site in IIS
3. SSL Settings: Require SSL
4. Added DNS name from certificate in `hosts` file
5. When opening 'https://<dns>/api/workitem' it does not complain about certificate anymore.
6. Updated Service Hool with the new https URL.

TFS does not run using SSL. It that the issue?

**Comment by jessehouwing** [comment]
Yes, tfs must run over SSL. Otherwise it won't open up the basic auth to
allow PAT access, though in theory we should be able to make it use NTLM /
Kernersville on-prem, that's not how the system is setup at the moment.
