### ISSUE TITLE
policyFilePath

### ISSUE THREAD

**Issue by maluht** [tfsaggregator/tfsaggregator-webhooks#18]
Hi

I have the following two problems with policyFilePath:

I would like to use the following pattern {CollectionId}.{TeamProject}.policies. I am unsure how to get the CollectionId of the collection, how would you do that?

I would like to put the policy file on a separate drive letter since I will be running multiple instances of aggregator behind a loadbalancer. It specifies that it’s a fixed path, could I do a value like U:\Policies\<ALL Policies>

Best regards
Mads

**Comment by giuliov** [comment]
Good question. The Id can be picked via the [REST API](https://www.visualstudio.com/en-us/docs/integrate/api/tfs/project-collections) e.g. typing in the browser `https://`_name-of-your-tfs_`/_apis/projectcollections`

Careful with drive mapping (they work only for a fully logged user, unusual for an AppPool), prefer a network path if you really have to (DFS might help), unless your `U:` is a clustered resource.

**Comment by maluht** [comment]
Thanks @giuliov, this was exactly what I was looking for.
