### ISSUE TITLE
Feature: Ability to write rules in a separate assembly

### ISSUE THREAD

**Issue by hegold** [tfsaggregator/tfsaggregator-webhooks#19]
To get the benefits of a real IDE, unit testing and debugging, it would be nice not to have to have to write code in XML files. An ideal solution might look something like:

```c#
[Rule]
[AppliesTo("Task")]
public void HelloWorldRule(IWorkItemExposed self, IWorkItemRepositoryExposed store, ILogger logger)
{
    logger.Log("Hello '{2}', World from {1} #{0}!", self.Id, self.TypeName, self["System.Title"]);
}
```

```xml
<policy name="SomePolicy">
  <ruleRef assembly="HelloWorldRules.dll" />
</policy>
```

**Comment by LSTANCZYK** [comment]
+1

**Comment by LSTANCZYK** [comment]
For now i created test project where I added all references and use the IDE to author rules, then copy paste to XML. Not ideal but works ok

**Comment by jessehouwing** [comment]
Can you share that project? I suppose it's helpful for others.
