### ISSUE TITLE
Aggregator Web App Response with 403 Error

### ISSUE THREAD

**Issue by thoaingan** [tfsaggregator/tfsaggregator-webhooks#25]
We installed the Aggregator Web App as instructed and everything works great for a few days, then we started getting 403 (Site Disabled) response when the VSTS Web Hook tries to connect to the Aggregator Web App. Please advise.

`Status Code: 403
Reason Phrase: Site Disabled
HTTP Version: 1.1
Headers:
{
  Date: Tue, 19 Jun 2018 20:40:21 GMT
  Server: Microsoft-IIS/10.0
  Content-Length: 2399
  Content-Type: text/html
}`

**Comment by jessehouwing** [comment]
Looks like the Azure web app hasn't been started.

**Comment by thoaingan** [comment]
We scaled up our App Service Plan, so hopefully this was caused by running over our Free app service plan minutes in Azure.

**Comment by thoaingan** [comment]
@jessehouwing Yes but we couldn't understand why it was shut down after running fine for some time. We scaled up the app service plan in Azure for more computing hours, so hopefully this was the root cause of the app being shut down.

**Comment by jessehouwing** [comment]
Hopefully.
