### ISSUE TITLE
The error "HTTP status code InternalServerError" in Functions Bot

### ISSUE THREAD

**Issue by Jessica1980** [tfsaggregator/tfsaggregator-webhooks#26]
Hi!
I'm using Functions Bot (instead of App Bot) and meet a problem that there is no web.config file when I create the Function Bot with Azure Subscription.
Could you please advise me how and where can I put information about MicrosoftAppId, MicrosoftAppPassword, AzureWebJobsStorage, QnASubscriptionKey, QnAKnowledgeBaseId?

I need it because I want to add HeroCard into my bot and I'm using [this](https://www.c-sharpcorner.com/article/how-to-add-image-or-video-response-to-microsoft-azure-bot-application/) insrution. In this instruction we should update web.config file. Without this my bot have the error "There was an error sending this message to your bot: HTTP status code InternalServerError"

**Comment by giuliov** [comment]
I really do not get what you ask. Can you clarify the context and what tfsaggregator has to do with bots?
