### ISSUE TITLE
Azure Deployment Failed

### ISSUE THREAD

**Issue by DeanClements** [tfsaggregator/tfsaggregator-webhooks#29]
Hi,

I have tried to use the Deploy to Azure option but receive the Deployment Failed message at the "Updating Website Config" stage the error message is "The current api-version doesn't support RBAC users. please use a newer version instead.(Code: Unauthorised)"

<img width="744" alt="image" src="https://user-images.githubusercontent.com/31061226/43783458-ac527198-9a59-11e8-903c-afd9f8815e63.png">

Thanks for any help you can provide
Dean

**Comment by jessehouwing** [comment]
Open the solution from the tfsaggregator/tfsaggregator/develop github
branch in Visual Studio 15.7, build it and right-click+publish.

**Comment by giuliov** [comment]
when I have an hour I will merge to master and update the README

**Comment by DeanClements** [comment]
Hi, thank you for your assistance, I have publish the current master branch to Azure, but I receive internal error 500 when I test the service hook from VSTS. hopefully once the current dev branch is merged, I won't have this issue.
 Thanks Dean

**Comment by giuliov** [comment]
The test button will always fail because it passes bogus data. I added some ad-hoc checks in the `develop` branch.

**Comment by DeanClements** [comment]
Hi, I still get internal 500 error if I actual create a work item in VSTS, as I have the service hook on the workitem create event.

The web.config does have the same username and password as I am passing via the service hook

the detailed error from the log stream of the app is below

</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 500.0 - Internal Server Error</h3> 
<h4>The page cannot be displayed because an internal server error has occurred.</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;ManagedPipelineHandler</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;System.Web.Http.WebHost.HttpControllerHandler</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://FF2tfsaggregator-webhooks09f8:80/api/workitem</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\home\site\wwwroot\api\workitem</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
 
</table> 
<div class="clear"></div> 
</div> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>More Information:</h4> 
This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x00000000,14393">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p>
