### ISSUE TITLE
Unable to Capture Errors in EventViewer

### ISSUE THREAD

**Issue by hagan01989** [tfsaggregator/tfsaggregator-webhooks#3]
I am using WebHooks 2.3 Beta
I am unable to see any events from TFSAggregator in EventViewer when using an account that has permission to write to the event log, and when deployed in debug configuration. Nothing showing up on Dbgview as well. Nothing in C:\Log default log location either. Trying to troubleshoot the below error and unable to without anything in logging. This is installed on an on-prem server, not Azure.

Status Code: 500
Reason Phrase: Internal Server Error
HTTP Version: 1.1
Headers:
{
  Cache-Control: private
  Date: Wed, 19 Apr 2017 16:06:54 GMT
  Server: Microsoft-IIS/8.0
  X-Powered-By: ASP.NET
  Content-Length: 4715
  Content-Type: text/html; charset=utf-8
}

**Comment by giuliov** [comment]
We have not reviewed the [Logging](https://tfsaggregator.github.io/admin/logging/) documentation page to match the Web Service version, sorry.

Logging for Web Service is different from the Server Plugin: everything is routed to .NET tracing infrastructure.
You need to edit the `web.config` and add/edit the `system.diagnostics` section.
In case you want to direct the logging to the Event Log look at the [EventLogTraceListener](https://msdn.microsoft.com/en-us/library/system.diagnostics.eventlogtracelistener.aspx), but I expect to see messages in the debug output.

**Comment by mbendtsen** [comment]
Was this ever fixed? I have the same issue with the same error message.

I have added this to Web.Config:
`  <system.diagnostics>
    <trace autoflush="false" indentsize="4">
      <listeners>
        <add name="myListener" 
          type="System.Diagnostics.TextWriterTraceListener" 
          initializeData="C:\Log\TFSAggregator.log" />
        <remove name="Default" />
      </listeners>
    </trace>
  </system.diagnostics>`

The file is created, but it is empty.

**Comment by giuliov** [comment]
Messages are lazy-written with `autoflush="false"`, which is good for a production environment. To debug/troubleshoot use `true`.
