### ISSUE TITLE
Error. A task was canceled.

### ISSUE THREAD

**Issue by arpsyapathy** [tfsaggregator/tfsaggregator-webhooks#30]
Hello!

Periodically, webhook in TFS reports an error:
```
A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.VisualStudio.Services.ServiceHooks.Common.HttpActionTask.<RunAsync>d__8.MoveNext()
```
These errors occur in the Feature. Judging by the logs, they occur when attaching child elements

My policies:
```
<?xml version="1.0" encoding="utf-8"?>
<AggregatorConfiguration>

  <runtime debug="true">
    <rateLimiting interval="00:00:30.00" changes="1000" />
    <logging level="Diagnostic" />
    <script language="C#" />
    <!--
    <authentication username="**DOMAIN**\**user**" password="***" />
    <authentication personalToken="**put-personal-token-here**" />
    -->
  </runtime>

  <rule name="SetEpic" hasFields="My.TargetRelease">
        <![CDATA[
        IWorkItemExposed topEpic = self.FollowingLinks("System.LinkTypes.Hierarchy-Reverse").WhereTypeIs("Epic").AtMost(1000).FirstOrDefault();
        if (topEpic != null)
        {
            string epicTitle = topEpic["Title"] as string;
            logger.Log("Parent Epic ID: {0}", topEpic.Id);
            self["My.TargetRelease"] = epicTitle;
            foreach (var x in self.Children)
            {
               x["My.TargetRelease"] = epicTitle;
            }
        }
        else
        {
      self["My.TargetRelease"] = "N/A";
            foreach (var x in self.Children)
            {
               x["My.TargetRelease"] = "N/A";
            }
        }
        ]]>
  </rule>
  <policy name="MyPolicy">
    <ruleRef name="SetEpic" />
  </policy>

</AggregatorConfiguration>

```

Do you have any ideas how to solve the problem? Thank you all in advance

**Comment by jessehouwing** [comment]
That query to look up the epics looks like it could take pretty long. We
currently don't have ways to increase timeouts etc.

Can't you look for epic with no parent, instead if grabbing all epics in
hierarchy?

**Comment by arpsyapathy** [comment]
@jessehouwing  Thank you for reply.

`Can't you look for epic with no parent, instead if grabbing all epics in
hierarchy?`
Could you give me an example of what you're saying? Thank you

**Comment by jessehouwing** [comment]
You can issue a raw WIQL query:

```
SELECT [System.Id], [System.Links.LinkType], [System.WorkItemType], [System.Title], [System.AssignedTo], [System.State], [System.Tags] FROM WorkItemLinks WHERE ([Source].[System.WorkItemType] = 'Epic') And ([System.Links.LinkType] = 'System.LinkTypes.Hierarchy-Reverse') And ([Target].[System.WorkItemType] &lt;&gt; '') ORDER BY [System.Id] mode(DoesNotContain)
```

**Comment by jessehouwing** [comment]
Looks like we don't have a way for you to run the raw query at the moment...

But the thing is, there is a timeout or other issue in executing the script, so it gets cancelled. TfsAggregator doesn't have a retry mechanism nor a failed queue. So the execution is lost.

**Comment by arpsyapathy** [comment]
@jessehouwing 
We found what the problem was. 
Generally, if the WorkItem many Child Items it creates too big a request and it cannot be processed and produces an error 500. 
And as a consequence of this error in the webhook. 
In our case, there were 600 Product Backlog Items in one Feature. And when we change this Feature (add description, or comment e.t.c.), a very large query was generated and we received a 500 error.
