### ISSUE TITLE
You do not have permission to view this directory or page. (Azure web service)

### ISSUE THREAD

**Issue by jdshkolnik** [tfsaggregator/tfsaggregator-webhooks#4]
Hi,

I deployed to Azure and, after it successfully completed, I navigated to the URL and got "You do not have permission to view this directory or page." Did I miss something in the instructions?

**Comment by giuliov** [comment]
The usual _gotcha_ is missing the stem `/api/workitem` from the URL

**Comment by jdshkolnik** [comment]
@giuliov My web hooks are failing. Where is the console app? I can't seem to find where to download it. I don't see a repo named "Aggregator.ConsoleApp' as implied by [this screenshot.](https://tfsaggregator.github.io/admin/console-app/console-app.png)

**Comment by giuliov** [comment]
@jdshkolnik these are three questions, let's take them in order.

1. Web hooks failing - you should [look at the logs](https://tfsaggregator.github.io/admin/logging/#capturing-log-on-azure); another user suggested (#2) that he was not able to manually create the subscriptions but he succeeded using PowerShell;
1. to get the console app, you can simply download the MSI from [a recent Release](https://github.com/tfsaggregator/tfsaggregator/releases) and install just the console;
1. the source code for the console app is part of the [Server Plugin repo](https://github.com/tfsaggregator/tfsaggregator/tree/master/Aggregator.ConsoleApp)

**Comment by jdshkolnik** [comment]
I was able to create subscriptions via PowerShell and manually. Logging is enabled but nothing is being produced. There is no Application folder in LogFiles.

The web hook test response is:

Status Code: 403
Reason Phrase: Forbidden
HTTP Version: 1.1
Headers:
{
  Transfer-Encoding: chunked
  Status: 403 Forbidden
  Vary: X-PJAX
  X-UA-Compatible: IE=Edge,chrome=1
  X-Request-Id: e640e20c5220c422669d35f3f06cde7c
  X-Runtime: 0.007776
  Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
  Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
  Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; pin-sha256="k2v657xBsOVe1PQRwOsHsw3bsGT2VzIqz5K+59sNQws="; pin-sha256="K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q="; pin-sha256="IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4="; pin-sha256="iie1VXtL7HzAMF+/PVPR9xzT80kQxdZeJ+zduCB3uj0="; pin-sha256="LvRiGEjRqfzurezaWuj8Wie2gyHMrW5Q06LspMnox7A="; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: deny
  X-XSS-Protection: 1; mode=block
  X-GitHub-Request-Id: 1A18:400F:251518B:39FECA2:5910A845
  Cache-Control: no-cache
  Date: Mon, 08 May 2017 17:17:57 GMT
  Set-Cookie: _gh_sess=eyJzZXNzaW9uX2lkIjoiMWYxMDRjOWNjNDc1M2RjMGI2NDBkNzMxYWU0ZTNhMzUiLCJsYXN0X3dyaXRlIjoxNDk0MjYzODc3MzY4fQ%3D%3D--29cb348f8fe8d6378cd9cfa160182ef3b107a096; path=/; secure; HttpOnly
  Server: GitHub.com
  Content-Type: text/plain; charset=utf-8
}
