### ISSUE TITLE
Pricing & Timescales

### ISSUE THREAD

**Issue by Mawdo81** [tfsaggregator/tfsaggregator-webhooks#6]
HI,
When will you be moving out of preview please, and what pricing do you expect to have past that point?
Thanks

**Comment by giuliov** [comment]
We recently discussed the free/pricing and the result was that the software will stay free and open source for the foreseeable future.
It may happen that some of us will offer paid support or extensions but this will not apply

Regarding the release status, we just need some time or additional contributor. There is some code to consolidate and we will start declaring Release Candidate.

**Comment by Mawdo81** [comment]
Perfect, thanks.
