### ISSUE TITLE
Deployement Failed

### ISSUE THREAD

**Issue by SebElior** [tfsaggregator/tfsaggregator-webhooks#8]
Hello,

I would deploy TfsAggregator on my VSTS with deploy.azure.com.
I am co-admin on Azure subcription and Project Collection Admin on VSTS.
But deployement failed:
![tfsa1](https://user-images.githubusercontent.com/28558936/31903307-0a7bff06-b828-11e7-967c-d2d68ced0508.png)
![tfsa2](https://user-images.githubusercontent.com/28558936/31903426-55943e18-b828-11e7-9aaf-f22ece757275.png)

Please help me

**Comment by giuliov** [comment]
The problem seems related to the permissions of your Azure account (Etat Unauthorized); the deployment is all done through [slingshot](https://github.com/projectkudu/slingshot), no VSTS involvement at this stage.
I remember that I had to setup AAD for the Azure subscription to make it working, HTH.
